# Generated by Django 5.2 on 2025-04-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('submission_due_date', models.DateField(blank=True, null=True)),
                ('feedback_due_date', models.DateField(blank=True, null=True)),
                ('competition_state', models.CharField(default='Upcoming', max_length=36)),
                ('submission_active', models.BooleanField(default=False)),
                ('feedback_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'competition',
            },
        ),
        migrations.CreateModel(
            name='LongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'long_answer',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('checkbox_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rubric',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('familyname', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='group', max_length=255)),
                ('comp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comp_groups', to='api.competition')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_grade_assigned', models.IntegerField(blank=True, null=True)),
                ('max_grade_assigned', models.IntegerField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('competition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comp_judges', to='api.competition')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='judge_info', to='api.userinfo')),
            ],
            options={
                'db_table': 'judge',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_checked', models.IntegerField(blank=True, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('judge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.judge')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='LongAnswerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.feedback')),
                ('long_answer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.longanswer')),
            ],
            options={
                'db_table': 'long_answer_feedback',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('familyname', models.CharField(blank=True, max_length=255, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_participants', to='api.group')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.AddField(
            model_name='longanswer',
            name='rubric',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='long_answers', to='api.rubric'),
        ),
        migrations.AddField(
            model_name='competition',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.rubric'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('rubric', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.rubric')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('rubric', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.rubric')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('min_text', models.CharField(blank=True, max_length=255, null=True)),
                ('max_text', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('rubric', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='api.rubric')),
            ],
            options={
                'db_table': 'scale',
            },
        ),
        migrations.CreateModel(
            name='ScaleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.feedback')),
                ('scale', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.scale')),
            ],
            options={
                'db_table': 'scale_feedback',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('problem_solved', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_link', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True)),
                ('log_book_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image_for_judges', models.ImageField(blank=True, null=True, upload_to='')),
                ('public_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.group')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.submission'),
        ),
    ]
